// Naukri.com CLI helpers
//
// Naukri.com is a client-side rendered React (Next.js) app. Its internal
// jobapi/v3 endpoints require a dynamic "nkparam" token generated by
// client-side JavaScript, making direct API calls infeasible.
//
// Strategy: We use Google's job search as a data source. Google indexes
// Naukri.com's job listings with structured data, making this reliable
// and respectful of both platforms' terms.
//
// Alternatively, for the web UI mode, we provide a curated search
// experience that constructs direct Naukri search URLs for the user.

export function writeError(error: string, code: string): void {
  process.stderr.write(JSON.stringify({ error, code }) + "\n")
}

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"

/** Fetch HTML with exponential backoff on 429/5xx. Returns "" on 404. */
export async function htmlFetch(url: string): Promise<string> {
  const maxRetries = 4
  let delay = 800
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try {
      const response = await fetch(url, {
        headers: {
          "User-Agent": UA,
          Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
          "Accept-Language": "en-US,en;q=0.9",
        },
        redirect: "follow",
        signal: AbortSignal.timeout(15000),
      })
      if (response.status === 429 || response.status >= 500) {
        if (attempt === maxRetries) {
          throw new Error(`Request failed: ${response.status} ${response.statusText}`)
        }
        const jitter = Math.floor(Math.random() * 500)
        await new Promise((r) => setTimeout(r, delay + jitter))
        delay = Math.min(delay * 2, 8000)
        continue
      }
      if (response.status === 404) return ""
      if (!response.ok) {
        throw new Error(`Request failed: ${response.status} ${response.statusText}`)
      }
      return response.text()
    } catch (e: any) {
      if (e.name === "AbortError" || e.name === "TimeoutError") {
        if (attempt === maxRetries) throw new Error("Request timed out after max retries")
        const jitter = Math.floor(Math.random() * 500)
        await new Promise((r) => setTimeout(r, delay + jitter))
        delay = Math.min(delay * 2, 8000)
        continue
      }
      throw e
    }
  }
  throw new Error("Request failed after max retries")
}

export interface JobCard {
  id: string
  title: string
  company: string | null
  companyUrl: string | null
  location: string | null
  experience: string | null
  salary: string | null
  date: string | null
  skills: string[]
  url: string
  description: string | null
}

export interface JobDetail extends JobCard {
  fullDescription: string | null
  employmentType: string | null
  industry: string | null
  education: string | null
  roleCategory: string | null
  isActive: boolean
}

/** Workplace-type flag for Naukri URL params: on-site=1, remote=2, hybrid=3. */
export function workTypeFlag(mode: string | undefined): string | null {
  switch ((mode || "").toLowerCase()) {
    case "remote":
    case "wfh":
      return "2"
    case "hybrid":
      return "3"
    case "onsite":
    case "wfo":
    case "on-site":
      return "1"
    default:
      return null
  }
}

/**
 * Build a Naukri.com search URL (the public SEO-friendly URL).
 * This URL is meant for display to the user / opening in a browser.
 */
export function buildNaukriUrl(opts: {
  query?: string
  location?: string
  experience?: number
  jobage?: number
  remote?: string
}): string {
  const keyword = (opts.query || "").toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "")
  const location = (opts.location || "").toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "")

  let base = "https://www.naukri.com/"
  if (keyword && location) base += `${keyword}-jobs-in-${location}`
  else if (keyword) base += `${keyword}-jobs`
  else if (location) base += `jobs-in-${location}`
  else base += `jobs`

  const params = new URLSearchParams()
  if (opts.experience !== undefined) params.set("experience", String(opts.experience))
  if (opts.jobage) params.set("jobAge", String(opts.jobage))
  const wfh = workTypeFlag(opts.remote)
  if (wfh) params.set("wfhType", wfh)

  const qs = params.toString()
  return qs ? `${base}?${qs}` : base
}

/**
 * Search for jobs using Google search, scoped to naukri.com, and parse
 * the structured snippets. This is the most reliable method since Naukri's
 * internal API requires dynamic tokens.
 */
export async function searchViaGoogle(opts: {
  query?: string
  location?: string
  experience?: number
  jobage?: number
  remote?: string
  limit: number
}): Promise<JobCard[]> {
  // Build Google search query scoped to naukri.com
  let googleQuery = "site:naukri.com/job-listings"
  if (opts.query) googleQuery += ` ${opts.query}`
  if (opts.location) googleQuery += ` ${opts.location}`
  if (opts.experience !== undefined) googleQuery += ` ${opts.experience} years`
  if (opts.remote === "remote") googleQuery += " remote work from home"

  const params = new URLSearchParams({
    q: googleQuery,
    num: String(Math.min(opts.limit, 20)),
  })
  if (opts.jobage) {
    // Google's tbs parameter for time-based filtering
    const tbs = opts.jobage <= 1 ? "qdr:d" : opts.jobage <= 3 ? "qdr:d3" : opts.jobage <= 7 ? "qdr:w" : opts.jobage <= 30 ? "qdr:m" : ""
    if (tbs) params.set("tbs", tbs)
  }

  const url = `https://www.google.com/search?${params.toString()}`

  const html = await htmlFetch(url)
  if (!html) return []

  return parseGoogleResults(html, opts.limit)
}

/** Parse Google search results to extract Naukri job listings. */
function parseGoogleResults(html: string, limit: number): JobCard[] {
  const results: JobCard[] = []

  // Google result links pointing to naukri.com/job-listings
  const linkPattern = /href="(https?:\/\/(?:www\.)?naukri\.com\/job-listings[^"]*?)"/gi
  const seen = new Set<string>()
  let match: RegExpExecArray | null

  while ((match = linkPattern.exec(html)) !== null && results.length < limit) {
    const rawUrl = decodeHtmlEntities(match[1]).split("&")[0] // strip Google tracking
    if (seen.has(rawUrl)) continue
    seen.add(rawUrl)

    // Parse the URL slug for metadata
    // Format: /job-listings-{title}-{company}-{location}-{id}
    const slug = rawUrl.replace(/.*\/job-listings-?/, "").replace(/\?.*/, "")
    const parts = slug.split("-")

    // Extract the ID (usually the last numeric segment or the end)
    const idMatch = rawUrl.match(/(\d{8,})/)
    const id = idMatch ? idMatch[1] : slug.slice(-12)

    // Try to parse title and company from Google snippet context
    // Look for the text around this URL in the HTML
    const urlIdx = html.indexOf(match[0])
    const context = html.slice(Math.max(0, urlIdx - 600), urlIdx + 600)

    // Google puts the title in <h3> tags
    const h3 = context.match(/<h3[^>]*>([\s\S]*?)<\/h3>/i)
    let title = h3 ? clean(h3[1]) : parseTitleFromSlug(slug)

    // Remove " - Naukri.com" suffix
    title = title.replace(/\s*[-–—]\s*Naukri\.com.*$/i, "").trim()

    // Extract snippet text for description and metadata
    const snippetMatch = context.match(/<span[^>]*class="[^"]*(?:st|VwiC3b)[^"]*"[^>]*>([\s\S]*?)<\/span>/i)
    const snippet = snippetMatch ? clean(snippetMatch[1]) : null

    // Try to extract company and location from snippet or title
    let company: string | null = null
    let location: string | null = null
    let experience: string | null = null
    let salary: string | null = null

    if (snippet) {
      // Common patterns in Naukri snippets
      const expMatch = snippet.match(/(\d+[-–]\d+\s*(?:Yrs?|Years?))/i)
      if (expMatch) experience = expMatch[1]

      const salMatch = snippet.match(/(₹?\s*[\d,.]+\s*[-–]\s*[\d,.]+\s*(?:Lakhs?|LPA|CTC|PA))/i)
      if (salMatch) salary = salMatch[1]
    }

    // Try to extract company from the slug
    // URL slugs often have format: title-company-location-exp-id
    const companyFromTitle = title.match(/(?:at|@|-)\s+(.+?)(?:\s+in\s+|\s*$)/i)
    if (companyFromTitle) {
      company = companyFromTitle[1].trim()
      title = title.replace(/\s*(?:at|@|-)\s+.+$/, "").trim()
    }

    results.push({
      id,
      title: title || "(untitled)",
      company,
      companyUrl: null,
      location,
      experience,
      salary,
      date: null,
      skills: [],
      url: rawUrl,
      description: snippet,
    })
  }

  return results
}

/** Parse a human-readable title from a URL slug. */
function parseTitleFromSlug(slug: string): string {
  // Remove common suffixes and IDs
  return slug
    .replace(/[-_](\d{5,}).*$/, "") // remove trailing IDs
    .replace(/-/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase())
    .trim()
}

export function decodeHtmlEntities(text: string): string {
  return text
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, (_, dec) => {
      const cp = parseInt(dec, 10)
      return cp >= 0 && cp <= 0x10ffff ? String.fromCodePoint(cp) : ""
    })
    .replace(/&#[xX]([0-9a-fA-F]+);/g, (_, hex) => {
      const cp = parseInt(hex, 16)
      return cp >= 0 && cp <= 0x10ffff ? String.fromCodePoint(cp) : ""
    })
    .replace(/&nbsp;/g, " ")
}

function stripTags(html: string): string {
  return html.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim()
}

export function clean(html: string): string {
  return decodeHtmlEntities(stripTags(html))
}

/** Parse a Naukri job detail page. Extracts what we can from the HTML. */
export function parseHtmlJobDetail(html: string, url: string): JobDetail {
  // Try to find the RSC payload containing job data
  const rscMatch = html.match(/self\.__next_f\.push\(\[1,"[\s\S]*?"jobDetails"[\s\S]*?\]\)/)

  const titleMatch = html.match(/<title>([^<]+)<\/title>/i)
  let title = titleMatch ? clean(titleMatch[1]) : "(untitled)"
  title = title.replace(/\s*[-–—|]\s*Naukri\.com.*$/i, "").trim()

  const idMatch = url.match(/(\d{8,})/)
  const id = idMatch ? idMatch[1] : url

  return {
    id,
    title,
    company: null,
    companyUrl: null,
    location: null,
    experience: null,
    salary: null,
    date: null,
    skills: [],
    url,
    description: null,
    fullDescription: null,
    employmentType: null,
    industry: null,
    education: null,
    roleCategory: null,
    isActive: !/expired|closed|no longer/i.test(html.slice(0, 5000)),
  }
}
