// Naukri.com CLI helpers
//
// Naukri.com is a client-side rendered React (Next.js) app. Its internal
// jobapi/v3 endpoints require a dynamic "nkparam" token generated by
// client-side JavaScript, making direct API calls infeasible.
//
// Strategy: We use DuckDuckGo's HTML search (no JS required) scoped to
// naukri.com to discover job listing URLs. Individual job pages on Naukri
// are also CSR-only, so `detail` extracts what it can from the HTML shell
// and tells the user to open the URL in a browser for the full listing.
//
// Personal use only. Keep volume low.

export function writeError(error: string, code: string): void {
  process.stderr.write(JSON.stringify({ error, code }) + "\n")
}

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"

/** Fetch HTML with exponential backoff on 429/5xx. Returns "" on 404. */
export async function htmlFetch(url: string): Promise<string> {
  const maxRetries = 4
  let delay = 800
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try {
      const response = await fetch(url, {
        headers: {
          "User-Agent": UA,
          Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
          "Accept-Language": "en-US,en;q=0.9",
        },
        redirect: "follow",
        signal: AbortSignal.timeout(15000),
      })
      if (response.status === 429 || response.status >= 500) {
        if (attempt === maxRetries) {
          throw new Error(`Request failed: ${response.status} ${response.statusText}`)
        }
        const jitter = Math.floor(Math.random() * 500)
        await new Promise((r) => setTimeout(r, delay + jitter))
        delay = Math.min(delay * 2, 8000)
        continue
      }
      if (response.status === 404) return ""
      if (!response.ok) {
        throw new Error(`Request failed: ${response.status} ${response.statusText}`)
      }
      return response.text()
    } catch (e: any) {
      if (e.name === "AbortError" || e.name === "TimeoutError") {
        if (attempt === maxRetries) throw new Error("Request timed out after max retries")
        const jitter = Math.floor(Math.random() * 500)
        await new Promise((r) => setTimeout(r, delay + jitter))
        delay = Math.min(delay * 2, 8000)
        continue
      }
      if (attempt === maxRetries) throw e
      const jitter = Math.floor(Math.random() * 500)
      await new Promise((r) => setTimeout(r, delay + jitter))
      delay = Math.min(delay * 2, 8000)
    }
  }
  throw new Error("Request failed after max retries")
}

export interface JobCard {
  id: string
  title: string
  company: string | null
  location: string | null
  experience: string | null
  salary: string | null
  date: string | null
  skills: string[]
  url: string
  description: string | null
}

export interface JobDetail extends JobCard {
  fullDescription: string | null
  employmentType: string | null
  industry: string | null
  isActive: boolean
}

/** Workplace-type param: on-site=1, remote=2, hybrid=3. */
export function workTypeFlag(mode: string | undefined): string | null {
  switch ((mode || "").toLowerCase()) {
    case "remote":
    case "wfh":
      return "2"
    case "hybrid":
      return "3"
    case "onsite":
    case "wfo":
    case "on-site":
      return "1"
    default:
      return null
  }
}

/**
 * Build a direct Naukri.com search URL. Users can open this in a browser.
 */
export function buildNaukriUrl(opts: {
  query?: string
  location?: string
  experience?: number
  jobage?: number
  remote?: string
}): string {
  const keyword = (opts.query || "").toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "")
  const location = (opts.location || "").toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "")

  let base = "https://www.naukri.com/"
  if (keyword && location) base += `${keyword}-jobs-in-${location}`
  else if (keyword) base += `${keyword}-jobs`
  else if (location) base += `jobs-in-${location}`
  else base += `jobs`

  const params = new URLSearchParams()
  if (opts.experience !== undefined) params.set("experience", String(opts.experience))
  if (opts.jobage) params.set("jobAge", String(opts.jobage))
  const wfh = workTypeFlag(opts.remote)
  if (wfh) params.set("wfhType", wfh)

  const qs = params.toString()
  return qs ? `${base}?${qs}` : base
}

/**
 * Search for Naukri.com jobs via DuckDuckGo's HTML endpoint.
 * DuckDuckGo serves results without requiring JavaScript, unlike Google.
 */
export async function searchViaDuckDuckGo(opts: {
  query?: string
  location?: string
  experience?: number
  jobage?: number
  remote?: string
  limit: number
}): Promise<JobCard[]> {
  // Build search query scoped to naukri.com job listings
  let searchQuery = "site:naukri.com"
  if (opts.query) searchQuery += ` ${opts.query}`
  if (opts.location) searchQuery += ` ${opts.location}`
  if (opts.experience !== undefined) searchQuery += ` ${opts.experience} years experience`
  if (opts.remote === "remote") searchQuery += " remote work from home"

  const params = new URLSearchParams({ q: searchQuery })
  const url = `https://html.duckduckgo.com/html/?${params.toString()}`

  const html = await htmlFetch(url)
  if (!html) return []

  return parseDDGResults(html, opts.limit)
}

/** Parse DuckDuckGo HTML search results. */
function parseDDGResults(html: string, limit: number): JobCard[] {
  const results: JobCard[] = []
  const seen = new Set<string>()

  // DuckDuckGo result pattern: <a class="result__a" href="...">title</a>
  // followed by <a class="result__snippet" href="...">snippet</a>
  const resultPattern = /class="result__a"[^>]*href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/gi
  const snippetPattern = /class="result__snippet"[^>]*>([\s\S]*?)<\/a>/gi

  // Collect all results and snippets
  const rawResults: Array<{ url: string; title: string }> = []
  let match: RegExpExecArray | null
  while ((match = resultPattern.exec(html)) !== null) {
    const rawUrl = decodeHtmlEntities(match[1])
    const title = clean(match[2])
    rawResults.push({ url: rawUrl, title })
  }

  const snippets: string[] = []
  while ((match = snippetPattern.exec(html)) !== null) {
    snippets.push(clean(match[1]))
  }

  for (let i = 0; i < rawResults.length && results.length < limit; i++) {
    let { url, title } = rawResults[i]

    // Extract actual URL from DDG redirect
    const uddgMatch = url.match(/uddg=([^&]+)/)
    if (uddgMatch) {
      url = decodeURIComponent(uddgMatch[1])
    }

    // Only include naukri.com results
    if (!url.includes("naukri.com")) continue
    if (seen.has(url)) continue
    seen.add(url)

    // Clean up title
    title = title
      .replace(/\s*[-–—|]\s*Naukri\.com.*$/i, "")
      .replace(/\s*-\s*\d+\s+.*?Job\s+(Vacancies|Opening).*$/i, "")
      .trim()

    const snippet = snippets[i] || null

    // Extract metadata from snippet
    let experience: string | null = null
    let salary: string | null = null
    let location: string | null = null

    if (snippet) {
      const expMatch = snippet.match(/(\d+[-–]\d+\s*(?:Yrs?|Years?))/i)
      if (expMatch) experience = expMatch[1]

      const salMatch = snippet.match(/(₹?\s*[\d,.]+\s*[-–]\s*[\d,.]+\s*(?:Lakhs?|LPA|CTC|PA))/i)
      if (salMatch) salary = salMatch[1]

      const locMatch = snippet.match(/(?:in|at)\s+([A-Z][a-zA-Z]+(?:\s*[,/]\s*[A-Z][a-zA-Z]+)*)/i)
      if (locMatch) location = locMatch[1]
    }

    // Generate an ID from the URL
    const idMatch = url.match(/(\d{8,})/)
    const id = idMatch ? idMatch[1] : String(results.length + 1)

    results.push({
      id,
      title: title || "(untitled)",
      company: null,
      location,
      experience,
      salary,
      date: null,
      skills: [],
      url,
      description: snippet,
    })
  }

  return results
}

export function decodeHtmlEntities(text: string): string {
  return text
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&#x27;/g, "'")
    .replace(/&#(\d+);/g, (_, dec) => {
      const cp = parseInt(dec, 10)
      return cp >= 0 && cp <= 0x10ffff ? String.fromCodePoint(cp) : ""
    })
    .replace(/&#[xX]([0-9a-fA-F]+);/g, (_, hex) => {
      const cp = parseInt(hex, 16)
      return cp >= 0 && cp <= 0x10ffff ? String.fromCodePoint(cp) : ""
    })
    .replace(/&nbsp;/g, " ")
}

function stripTags(html: string): string {
  return html.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim()
}

export function clean(html: string): string {
  return decodeHtmlEntities(stripTags(html))
}

/** Parse a Naukri job detail page. Extracts title from the HTML shell. */
export function parseHtmlJobDetail(html: string, url: string): JobDetail {
  const titleMatch = html.match(/<title>([^<]+)<\/title>/i)
  let title = titleMatch ? clean(titleMatch[1]) : "(untitled)"
  title = title.replace(/\s*[-–—|]\s*Naukri\.com.*$/i, "").trim()

  const idMatch = url.match(/(\d{8,})/)
  const id = idMatch ? idMatch[1] : url

  return {
    id,
    title,
    company: null,
    location: null,
    experience: null,
    salary: null,
    date: null,
    skills: [],
    url,
    description: null,
    fullDescription: null,
    employmentType: null,
    industry: null,
    isActive: !/expired|closed|no longer/i.test(html.slice(0, 5000)),
  }
}
